import type {
  CandidateAction,
  Goal,
  ModuleContext,
  Proposal,
  SideEffectLevel,
  Reasoner
} from "@neurocore/protocol";
import type { OpenAICompatibleConfig } from "../config/openai-compatible-config.js";
import { appendDebugFile, debugLog } from "../debug.js";

interface ChatCompletionResponse {
  choices?: Array<{
    finish_reason?: string | null;
    message?: {
      content?: string | Array<{ type?: string; text?: string }>;
    };
  }>;
}

interface ProposalJson {
  proposal_type?: Proposal["proposal_type"];
  salience_score?: number;
  confidence?: number;
  risk?: number;
  explanation?: string;
  payload?: Record<string, unknown>;
}

interface ActionJson {
  action_type?: CandidateAction["action_type"];
  title?: string;
  description?: string;
  tool_name?: string;
  tool_args?: Record<string, unknown>;
  expected_outcome?: string;
  preconditions?: string[];
  depends_on_action_ids?: string[];
  next_action_id_on_success?: string;
  next_action_id_on_failure?: string;
  plan_group_id?: string;
  side_effect_level?: CandidateAction["side_effect_level"];
}

interface PlanResultJson {
  proposals?: ProposalJson[];
}

interface RespondResultJson {
  actions?: ActionJson[];
}

interface ToolCatalogEntry {
  name?: string;
  description?: string;
  sideEffectLevel?: SideEffectLevel;
  inputSchema?: Record<string, unknown>;
  outputSchema?: Record<string, unknown>;
}

interface NormalizedActionJson extends ActionJson {
  action_type: CandidateAction["action_type"];
}

interface ResponseLike {
  ok: boolean;
  status: number;
  statusText: string;
  text?: () => Promise<string>;
  json?: () => Promise<unknown>;
}

interface ChatCompletionChunk {
  choices?: Array<{
    delta?: {
      content?: string | Array<{ type?: string; text?: string }>;
    };
    finish_reason?: string | null;
  }>;
}

const DEFAULT_MAX_OUTPUT_TOKENS = 31_999;
const DEFAULT_TEMPERATURE = 0.2;
const MIN_RETRY_MAX_OUTPUT_TOKENS = 4096;

export interface OpenAICompatibleReasonerOptions {
  temperature?: number;
  max_tokens?: number;
  maxOutputTokens?: number;
  fetch?: typeof fetch;
  disableLocalFallback?: boolean;
}

export class OpenAICompatibleReasoner implements Reasoner {
  public readonly name = "openai-compatible-reasoner";
  private readonly directResponses = new WeakMap<CandidateAction, string>();

  public constructor(
    private readonly config: OpenAICompatibleConfig,
    private readonly options: OpenAICompatibleReasonerOptions = {}
  ) {}

  public async plan(ctx: ModuleContext): Promise<Proposal[]> {
    const cycleId = ctx.session.current_cycle_id ?? ctx.services.generateId("cyc");
    debugLog("reasoner", "Starting planning request", {
      sessionId: ctx.session.session_id,
      cycleId,
      model: this.config.model,
      goalCount: ctx.goals.length,
      toolCount: ctx.profile.tool_refs.length
    });

    try {
      const json = await this.completeJson<PlanResultJson>(
        buildPlanSystemPrompt(),
        buildPlanUserPrompt(ctx)
      );
      const proposals = (json.proposals ?? [])
        .slice(0, 3)
        .map((proposal) => ({
          proposal_id: ctx.services.generateId("prp"),
          schema_version: ctx.profile.schema_version,
          session_id: ctx.session.session_id,
          cycle_id: cycleId,
          module_name: this.name,
          proposal_type: proposal.proposal_type ?? "plan",
          salience_score: clampScore(proposal.salience_score, 0.6),
          confidence: clampScore(proposal.confidence, 0.6),
          risk: clampScore(proposal.risk, 0.1),
          payload: proposal.payload ?? {
            summary: "Model returned no plan payload."
          },
          explanation: proposal.explanation ?? "Generated by the model-backed planning path."
        }));

      if (proposals.length > 0) {
        debugLog("reasoner", "Planning request completed", {
          sessionId: ctx.session.session_id,
          cycleId,
          proposalCount: proposals.length
        });
        return proposals;
      }
    } catch (error) {
      if (this.options.disableLocalFallback) {
        throw error;
      }
      debugLog("reasoner", "Planning request failed, falling back to local plan", {
        sessionId: ctx.session.session_id,
        cycleId,
        errorMessage: error instanceof Error ? error.message : String(error)
      });
    }

    const fallbackProposal = buildFallbackPlanProposal(ctx, cycleId);
    debugLog("reasoner", "Using fallback local plan proposal", {
      sessionId: ctx.session.session_id,
      cycleId
    });
    return [fallbackProposal];
  }

  public async respond(ctx: ModuleContext): Promise<CandidateAction[]> {
    const currentInputContent =
      typeof ctx.runtime_state.current_input_content === "string"
        ? ctx.runtime_state.current_input_content
        : "";
    const toolCatalog = getToolCatalog(ctx);
    const knownTools = new Set(ctx.profile.tool_refs);

    debugLog("reasoner", "Starting action selection request", {
      sessionId: ctx.session.session_id,
      cycleId: ctx.session.current_cycle_id ?? "pending",
      model: this.config.model,
      toolCount: ctx.profile.tool_refs.length,
      goalCount: ctx.goals.length,
      contextChars: currentInputContent.length
    });

    let json: RespondResultJson;
    try {
      json = await this.completeJson<RespondResultJson>(
        buildRespondSystemPrompt(),
        buildRespondUserPrompt(ctx)
      );
    } catch (error) {
      if (this.options.disableLocalFallback) {
        throw error;
      }
      debugLog("reasoner", "Action selection request failed, using fallback ask_user action", {
        sessionId: ctx.session.session_id,
        cycleId: ctx.session.current_cycle_id ?? "pending",
        errorMessage: error instanceof Error ? error.message : String(error)
      });
      return [this.createDirectFallbackAction(ctx, buildFallbackAskUserAction(error))];
    }

    const actions = json.actions ?? [];
    if (actions.length === 0) {
      debugLog("reasoner", "Model returned no actions, using fallback ask_user action", {
        sessionId: ctx.session.session_id
      });
      return [
        this.createDirectFallbackAction(ctx, {
          action_type: "ask_user",
          title: "Clarify the request",
          description: "Model returned no structured actions, ask the user for clarification.",
          expected_outcome: "Collect missing information before continuing.",
          side_effect_level: "none"
        })
      ];
    }

    const mapped = actions
      .map((action) => normalizeAction(action, knownTools))
      .filter((action): action is NormalizedActionJson => action !== null)
      .map((action) => {
        const toolSideEffectLevel = resolveToolSideEffectLevel(action, toolCatalog);
        return {
          action_id: ctx.services.generateId("act"),
          action_type: action.action_type,
          title: action.title ?? "Untitled action",
          description: action.description,
          tool_name: action.tool_name,
          tool_args: action.tool_args,
          expected_outcome: action.expected_outcome,
          preconditions: action.preconditions,
          depends_on_action_ids: action.depends_on_action_ids,
          next_action_id_on_success: action.next_action_id_on_success,
          next_action_id_on_failure: action.next_action_id_on_failure,
          plan_group_id: action.plan_group_id,
          side_effect_level:
            toolSideEffectLevel ?? action.side_effect_level ?? inferSideEffectLevel(action)
        };
      });

    if (mapped.length === 0) {
      debugLog("reasoner", "Model actions were invalid for the available tool catalog", {
        sessionId: ctx.session.session_id,
        cycleId: ctx.session.current_cycle_id ?? "pending"
      });
      return [
        this.createDirectFallbackAction(ctx, {
          action_type: "ask_user",
          title: "Clarify the request",
          description: "Model proposed unsupported tool actions, ask the user for clarification.",
          expected_outcome: "Collect a request that matches the available toolset.",
          side_effect_level: "none"
        })
      ];
    }

    debugLog("reasoner", "Action selection completed", {
      sessionId: ctx.session.session_id,
      actionCount: mapped.length,
      actionTypes: mapped.map((action) => action.action_type),
      toolNames: mapped.map((action) => action.tool_name).filter(Boolean)
    });

    return mapped;
  }

  public async *streamText(
    ctx: ModuleContext,
    action: CandidateAction
  ): AsyncIterable<string> {
    if (action.action_type !== "respond" && action.action_type !== "ask_user") {
      throw new Error(`streamText only supports respond/ask_user actions, got ${action.action_type}.`);
    }

    const directResponse = this.directResponses.get(action);
    if (directResponse) {
      yield directResponse;
      return;
    }

    const controller = new AbortController();
    const timeoutMs = this.config.streamTimeoutMs ?? this.config.timeoutMs ?? 60_000;
    const timeout = setTimeout(
      () => controller.abort(new Error(`Model stream request timed out after ${timeoutMs}ms.`)),
      timeoutMs
    );
    const url = resolveChatCompletionsUrl(this.config.apiUrl);
    const requestPayload = {
      ...this.config.extraBody,
      model: this.config.model,
      temperature: this.options.temperature ?? DEFAULT_TEMPERATURE,
      stream: true,
      max_tokens: this.options.max_tokens ?? this.options.maxOutputTokens ?? DEFAULT_MAX_OUTPUT_TOKENS,
      messages: [
        { role: "system", content: buildTextStreamSystemPrompt(action) },
        { role: "user", content: buildTextStreamUserPrompt(ctx, action) }
      ]
    };

    try {
      const fetchImpl = this.options.fetch ?? fetch;
      const response = await fetchImpl(url, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: `Bearer ${this.config.bearerToken}`,
          ...this.config.headers
        },
        body: JSON.stringify(requestPayload),
        signal: controller.signal
      });

      if (!response.ok) {
        const responseText = await readResponseText(response);
        throw new Error(
          `Streamed text request failed with ${response.status} ${response.statusText}: ${responseText}`
        );
      }

      if (!response.body) {
        throw new Error("Model response did not provide a readable stream.");
      }

      for await (const delta of readChatCompletionStream(response.body)) {
        if (delta) {
          yield delta;
        }
      }
    } finally {
      clearTimeout(timeout);
    }
  }

  private async completeJson<T>(systemPrompt: string, userPrompt: string): Promise<T> {
    const firstBudget =
      this.options.max_tokens ?? this.options.maxOutputTokens ?? DEFAULT_MAX_OUTPUT_TOKENS;
    const retryBudget = Math.max(firstBudget, MIN_RETRY_MAX_OUTPUT_TOKENS);

    try {
      return await this.completeJsonOnce<T>(systemPrompt, userPrompt, firstBudget);
    } catch (error) {
      if (!isRetriableJsonParseError(error) || retryBudget === firstBudget) {
        throw error;
      }

      debugLog("reasoner", "Retrying model request after JSON parse failure", {
        model: this.config.model,
        firstBudget,
        retryBudget,
        errorMessage: error instanceof Error ? error.message : String(error)
      });

      return this.completeJsonOnce<T>(systemPrompt, userPrompt, retryBudget);
    }
  }

  private async completeJsonOnce<T>(
    systemPrompt: string,
    userPrompt: string,
    maxOutputTokens: number
  ): Promise<T> {
    const controller = new AbortController();
    const timeoutMs = this.config.jsonTimeoutMs ?? this.config.timeoutMs ?? 60_000;
    const timeout = setTimeout(
      () => controller.abort(new Error(`Model request timed out after ${timeoutMs}ms.`)),
      timeoutMs
    );
    const url = resolveChatCompletionsUrl(this.config.apiUrl);
    const startedAt = Date.now();
    const temperature = this.options.temperature ?? DEFAULT_TEMPERATURE;
    const requestPayload = {
      ...this.config.extraBody,
      model: this.config.model,
      temperature,
      max_tokens: maxOutputTokens,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ]
    };

    try {
      debugLog("reasoner", "Sending model request", {
        model: this.config.model,
        url,
        timeoutMs,
        temperature,
        maxOutputTokens,
        systemPromptChars: systemPrompt.length,
        userPromptChars: userPrompt.length
      });
      await appendDebugFile("reasoner", "model-request", {
        url,
        timeoutMs,
        request: requestPayload
      });

      const fetchImpl = this.options.fetch ?? fetch;
      const response = await fetchImpl(url, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: `Bearer ${this.config.bearerToken}`,
          ...this.config.headers
        },
        body: JSON.stringify(requestPayload),
        signal: controller.signal
      });

      const latencyMs = Date.now() - startedAt;
      debugLog("reasoner", "Received model response headers", {
        model: this.config.model,
        url,
        status: response.status,
        ok: response.ok,
        latencyMs
      });

      const responseText = await readResponseText(response);
      await appendDebugFile("reasoner", "model-response", {
        url,
        status: response.status,
        ok: response.ok,
        statusText: response.statusText,
        latencyMs,
        response: responseText
      });

      if (!response.ok) {
        debugLog("reasoner", "Model request failed", {
          model: this.config.model,
          status: response.status,
          latencyMs,
          errorPreview: responseText.slice(0, 300)
        });
        throw new Error(
          `Model request failed with ${response.status} ${response.statusText}: ${responseText}`
        );
      }

      const data = JSON.parse(responseText) as ChatCompletionResponse;
      const content = extractContent(data);
      const finishReason = data.choices?.[0]?.finish_reason ?? null;
      debugLog("reasoner", "Parsed model response content", {
        model: this.config.model,
        latencyMs,
        finishReason,
        contentChars: content.length,
        contentPreview: content.slice(0, 200)
      });
      return parseJsonResponse<T>(content);
    } catch (error) {
      const latencyMs = Date.now() - startedAt;
      await appendDebugFile("reasoner", "model-error", {
        url,
        latencyMs,
        errorName: error instanceof Error ? error.name : "UnknownError",
        errorMessage: error instanceof Error ? error.message : String(error)
      });
      debugLog("reasoner", "Model request threw", {
        model: this.config.model,
        url,
        latencyMs,
        maxOutputTokens,
        errorName: error instanceof Error ? error.name : "UnknownError",
        errorMessage: error instanceof Error ? error.message : String(error)
      });
      throw error;
    } finally {
      clearTimeout(timeout);
    }
  }

  private createDirectFallbackAction(
    ctx: ModuleContext,
    action: Omit<CandidateAction, "action_id">
  ): CandidateAction {
    const candidate = {
      action_id: ctx.services.generateId("act"),
      ...action
    };
    this.directResponses.set(candidate, candidate.description ?? candidate.title);
    return candidate;
  }
}

function resolveChatCompletionsUrl(apiUrl: string): string {
  const normalized = apiUrl.replace(/\/+$/, "");
  if (normalized.endsWith("/chat/completions")) {
    return normalized;
  }
  return `${normalized}/chat/completions`;
}

function extractContent(response: ChatCompletionResponse): string {
  const content = response.choices?.[0]?.message?.content;
  if (typeof content === "string") {
    return stripMarkdownCodeFence(content);
  }
  if (Array.isArray(content)) {
    const joined = content.map((part) => part.text ?? "").join("");
    return stripMarkdownCodeFence(joined);
  }
  throw new Error("Model response did not include message content.");
}

function extractChunkContent(response: ChatCompletionChunk): string {
  const content = response.choices?.[0]?.delta?.content;
  if (typeof content === "string") {
    return content;
  }
  if (Array.isArray(content)) {
    return content.map((part) => part.text ?? "").join("");
  }
  return "";
}

async function* readChatCompletionStream(stream: ReadableStream<Uint8Array>): AsyncIterable<string> {
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let pendingText = "";

  while (true) {
    const chunk = await reader.read();
    if (chunk.done) {
      break;
    }

    buffer += decoder.decode(chunk.value, { stream: true });
    while (true) {
      const boundary = buffer.indexOf("\n\n");
      if (boundary < 0) {
        break;
      }

      const rawEvent = buffer.slice(0, boundary);
      buffer = buffer.slice(boundary + 2);
      const dataLines = rawEvent
        .split("\n")
        .filter((line) => line.startsWith("data:"))
        .map((line) => line.slice(5).trim());

      if (dataLines.length === 0) {
        continue;
      }

      const data = dataLines.join("\n");
      if (data === "[DONE]") {
        return;
      }

      const parsed = JSON.parse(data) as ChatCompletionChunk;
      const delta = extractChunkContent(parsed);
      if (delta) {
        pendingText += delta;
        if (shouldFlushStreamChunk(pendingText)) {
          yield pendingText;
          pendingText = "";
        }
      }
    }
  }

  if (pendingText) {
    yield pendingText;
  }
}

function shouldFlushStreamChunk(text: string): boolean {
  if (text.length >= 24) {
    return true;
  }

  return /[\n。！？!?.,;:)]$/.test(text);
}

async function readResponseText(response: ResponseLike): Promise<string> {
  if (typeof response.text === "function") {
    return response.text();
  }

  if (typeof response.json === "function") {
    const payload = await response.json();
    return JSON.stringify(payload);
  }

  throw new Error("Model response body could not be read.");
}

function stripMarkdownCodeFence(value: string): string {
  return value.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim();
}

function parseJsonResponse<T>(content: string): T {
  try {
    return JSON.parse(content) as T;
  } catch {
    const extracted = extractFirstJsonObject(content);
    return JSON.parse(extracted) as T;
  }
}

function isRetriableJsonParseError(error: unknown): boolean {
  if (!(error instanceof Error)) {
    return false;
  }

  const message = error.message.toLowerCase();
  return (
    message.includes("incomplete json") ||
    message.includes("unexpected end of json input") ||
    message.includes("unterminated string")
  );
}

function extractFirstJsonObject(content: string): string {
  const start = content.search(/[\[{]/);
  if (start < 0) {
    throw new Error("Model response did not contain JSON.");
  }

  const stack: string[] = [];
  let inString = false;
  let escaped = false;

  for (let index = start; index < content.length; index += 1) {
    const char = content[index];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
      continue;
    }

    if (char === "{" || char === "[") {
      stack.push(char);
      continue;
    }

    if (char === "}" || char === "]") {
      const expected = char === "}" ? "{" : "[";
      if (stack.at(-1) === expected) {
        stack.pop();
      }
      if (stack.length === 0) {
        return content.slice(start, index + 1);
      }
    }
  }

  if (!inString && stack.length > 0) {
    const suffix = stack
      .slice()
      .reverse()
      .map((char) => (char === "{" ? "}" : "]"))
      .join("");
    return `${content.slice(start)}${suffix}`;
  }

  throw new Error("Model response contained incomplete JSON.");
}

function clampScore(value: number | undefined, fallback: number): number {
  if (typeof value !== "number" || Number.isNaN(value)) {
    return fallback;
  }
  return Math.max(0, Math.min(1, value));
}

function inferSideEffectLevel(action: ActionJson): CandidateAction["side_effect_level"] {
  return action.action_type === "call_tool" ? "medium" : "none";
}

function isValidActionType(value: unknown): value is CandidateAction["action_type"] {
  return (
    value === "respond" ||
    value === "ask_user" ||
    value === "call_tool" ||
    value === "update_goal" ||
    value === "write_memory" ||
    value === "delegate" ||
    value === "wait" ||
    value === "complete" ||
    value === "abort"
  );
}

function normalizeAction(
  action: ActionJson,
  knownTools: Set<string>
): NormalizedActionJson | null {
  let actionType = isValidActionType(action.action_type) ? action.action_type : undefined;
  let toolName = action.tool_name;

  if (!actionType && typeof action.action_type === "string" && knownTools.has(action.action_type)) {
    actionType = "call_tool";
    toolName ??= action.action_type;
  }

  if (!actionType && typeof toolName === "string" && knownTools.has(toolName)) {
    actionType = "call_tool";
  }

  if (!actionType) {
    actionType = "respond";
  }

  if (actionType === "call_tool") {
    if (typeof toolName !== "string" || !knownTools.has(toolName)) {
      return null;
    }
  } else {
    toolName = undefined;
  }

  return {
    ...action,
    action_type: actionType,
    tool_name: toolName,
    preconditions: normalizePreconditions(action.preconditions),
    depends_on_action_ids: Array.isArray(action.depends_on_action_ids)
      ? action.depends_on_action_ids.filter((value): value is string => typeof value === "string" && value.trim().length > 0)
      : undefined,
    next_action_id_on_success:
      typeof action.next_action_id_on_success === "string" && action.next_action_id_on_success.trim().length > 0
        ? action.next_action_id_on_success
        : undefined,
    next_action_id_on_failure:
      typeof action.next_action_id_on_failure === "string" && action.next_action_id_on_failure.trim().length > 0
        ? action.next_action_id_on_failure
        : undefined,
    plan_group_id:
      typeof action.plan_group_id === "string" && action.plan_group_id.trim().length > 0
        ? action.plan_group_id
        : undefined
  };
}

function normalizePreconditions(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }

  const preconditions = value
    .filter((entry): entry is string => typeof entry === "string")
    .map((entry) => entry.trim())
    .filter((entry) => isRuntimePrecondition(entry));
  return preconditions.length > 0 ? preconditions : undefined;
}

function isRuntimePrecondition(value: string): boolean {
  return (
    value === "input:structured_response=present" ||
    /^session:state=[a-z_]+$/.test(value) ||
    /^tool:[^:]+:registered=(true|false)$/.test(value) ||
    /^entity:[^:]+:[^=]+=.+$/.test(value)
  );
}

function buildPlanSystemPrompt(): string {
  return [
    "You are the planning module of a structured agent runtime.",
    "Return JSON only.",
    'Output shape: {"proposals":[{"proposal_type":"plan","salience_score":0.0,"confidence":0.0,"risk":0.0,"explanation":"...","payload":{"summary":"..."}}]}',
    "Use scores in the range [0,1].",
    "Ground the plan in the current goals, available tools, recalled memory, and current context.",
    "Do not include markdown or commentary outside JSON."
  ].join("\n");
}

function buildRespondSystemPrompt(): string {
  return [
    "Structured agent runtime action selector.",
    "Return JSON only.",
    'Shape: {"actions":[{"action_type":"ask_user|respond|call_tool|complete|abort","title":"...","description":"...","tool_name":"...","tool_args":{},"expected_outcome":"...","preconditions":["..."],"depends_on_action_ids":["act-1"],"next_action_id_on_success":"act-2","next_action_id_on_failure":"act-3","plan_group_id":"plan-a","side_effect_level":"none|low|medium|high"}]}',
    "Use at most 2 actions.",
    "Only use tool names provided in the tool catalog.",
    "Use recalled memory and previous tool observations to decide the next step.",
    "If prior evidence is insufficient, call the next necessary tool. If evidence is sufficient, respond or complete.",
    "For destructive or production-impacting tools, preserve a high side_effect_level and include preconditions.",
    "When a task has a deterministic continuation or fallback, connect actions with depends_on_action_ids and next_action_id_on_success or next_action_id_on_failure.",
    "For respond or complete actions, put the exact user-facing answer in description. Do not write meta-instructions like 'provide diagnosis' or 'summarize result'.",
    "Keep each action compact enough to fit in a single JSON response without truncation.",
    "Prefer concise outputs."
  ].join("\n");
}

function buildPlanUserPrompt(ctx: ModuleContext): string {
  const memoryRecall = Array.isArray(ctx.runtime_state.memory_recall_proposals)
    ? ctx.runtime_state.memory_recall_proposals.map(summarizeMemoryProposal)
    : [];

  return JSON.stringify(
    {
      role: ctx.profile.role,
      domain: ctx.profile.domain,
      activeGoals: ctx.goals.map(summarizeGoal),
      availableTools: getToolCatalog(ctx),
      memoryRecall,
      workspace: ctx.workspace
        ? {
            contextSummary: ctx.workspace.context_summary,
            candidateActions: ctx.workspace.candidate_actions,
            memoryDigest: ctx.workspace.memory_digest
          }
        : null
    },
    null,
    2
  );
}

function buildRespondUserPrompt(ctx: ModuleContext): string {
  const memoryRecall = Array.isArray(ctx.runtime_state.memory_recall_proposals)
    ? ctx.runtime_state.memory_recall_proposals.map(summarizeMemoryProposal)
    : [];
  const conversationHistory = Array.isArray(ctx.runtime_state.conversation_history)
    ? ctx.runtime_state.conversation_history
    : [];

  return JSON.stringify(
    {
      role: ctx.profile.role,
      goals: ctx.goals.map(summarizeGoal),
      tools: getToolCatalog(ctx),
      memoryRecall,
      conversationHistory,
      conversationSummary:
        typeof ctx.runtime_state.conversation_summary === "string"
          ? ctx.runtime_state.conversation_summary
          : null,
      conversationHistoryTokens: ctx.runtime_state.conversation_history_tokens ?? null,
      conversationHistoryTruncated: ctx.runtime_state.conversation_history_truncated ?? false,
      context: typeof ctx.runtime_state.current_input_content === "string"
        ? ctx.runtime_state.current_input_content
        : ctx.workspace?.context_summary ?? null,
      inputMetadata: ctx.runtime_state.current_input_metadata ?? null,
      inputContentParts: Array.isArray(ctx.runtime_state.current_input_parts)
        ? ctx.runtime_state.current_input_parts
        : [],
      structuredResponse: ctx.runtime_state.current_input_structured_response ?? null,
      workspace: ctx.workspace
        ? {
            memoryDigest: ctx.workspace.memory_digest,
            candidateActions: ctx.workspace.candidate_actions
          }
        : null
    },
    null,
    2
  );
}

function buildTextStreamSystemPrompt(action: CandidateAction): string {
  return [
    "You are the user-facing response composer inside a structured agent runtime.",
    "Return plain text only.",
    action.action_type === "ask_user"
      ? "Produce a concise follow-up question that asks only for the missing information."
      : "Produce the final assistant reply for the user.",
    "Do not emit JSON, markdown fences, XML, or meta commentary.",
    "Use the selected action, current context, active goals, and workspace state."
  ].join("\n");
}

function buildTextStreamUserPrompt(ctx: ModuleContext, action: CandidateAction): string {
  return JSON.stringify(
    {
      role: ctx.profile.role,
      goals: ctx.goals.map(summarizeGoal),
      conversationHistory: Array.isArray(ctx.runtime_state.conversation_history)
        ? ctx.runtime_state.conversation_history
        : [],
      conversationSummary:
        typeof ctx.runtime_state.conversation_summary === "string"
          ? ctx.runtime_state.conversation_summary
          : null,
      conversationHistoryTokens: ctx.runtime_state.conversation_history_tokens ?? null,
      conversationHistoryTruncated: ctx.runtime_state.conversation_history_truncated ?? false,
      context:
        typeof ctx.runtime_state.current_input_content === "string"
          ? ctx.runtime_state.current_input_content
          : ctx.workspace?.context_summary ?? null,
      inputMetadata: ctx.runtime_state.current_input_metadata ?? null,
      inputContentParts: Array.isArray(ctx.runtime_state.current_input_parts)
        ? ctx.runtime_state.current_input_parts
        : [],
      structuredResponse: ctx.runtime_state.current_input_structured_response ?? null,
      selectedAction: {
        action_type: action.action_type,
        title: action.title,
        description: action.description,
        expected_outcome: action.expected_outcome,
        preconditions: action.preconditions
      },
      workspace: ctx.workspace
        ? {
            contextSummary: ctx.workspace.context_summary,
            memoryDigest: ctx.workspace.memory_digest
          }
        : null
    },
    null,
    2
  );
}

function buildFallbackPlanProposal(
  ctx: ModuleContext,
  cycleId: string
): Proposal {
  const goalTitles = ctx.goals.map((goal) => goal.title).filter(Boolean);
  const summary =
    goalTitles.length > 0
      ? `Pursue active goals: ${goalTitles.join("; ")}`
      : `Act according to role: ${ctx.profile.role}`;

  return {
    proposal_id: ctx.services.generateId("prp"),
    schema_version: ctx.profile.schema_version,
    session_id: ctx.session.session_id,
    cycle_id: cycleId,
    module_name: "openai-compatible-reasoner",
    proposal_type: "plan",
    salience_score: 0.6,
    confidence: 0.6,
    risk: 0.1,
    payload: {
      summary,
      toolRefs: ctx.profile.tool_refs
    },
    explanation: "Fallback local plan after model planning failed."
  };
}

function summarizeGoal(goal: Goal) {
  return {
    goalId: goal.goal_id,
    title: goal.title,
    description: goal.description,
    status: goal.status,
    priority: goal.priority
  };
}

function summarizeMemoryProposal(proposal: unknown) {
  if (!proposal || typeof proposal !== "object") {
    return null;
  }

  const payload =
    "payload" in proposal && proposal.payload && typeof proposal.payload === "object"
      ? proposal.payload
      : null;
  const entries =
    payload && "entries" in payload && Array.isArray(payload.entries)
      ? payload.entries.map((entry) =>
          typeof entry === "object" && entry !== null ? (entry as { summary?: string }).summary : null
        )
      : [];
  const episodes =
    payload && "episodes" in payload && Array.isArray(payload.episodes)
      ? payload.episodes.map((episode) => {
          if (!episode || typeof episode !== "object") {
            return null;
          }
          const metadata =
            "metadata" in episode && episode.metadata && typeof episode.metadata === "object"
              ? episode.metadata
              : null;
          return {
            selectedStrategy:
              "selected_strategy" in episode ? episode.selected_strategy : undefined,
            outcome: "outcome" in episode ? episode.outcome : undefined,
            outcomeSummary:
              "outcome_summary" in episode ? episode.outcome_summary : undefined,
            toolName:
              metadata && "tool_name" in metadata ? metadata.tool_name : undefined
          };
        })
      : [];

  return {
    module: "module_name" in proposal ? proposal.module_name : undefined,
    explanation: "explanation" in proposal ? proposal.explanation : undefined,
    entries: entries.filter(Boolean),
    episodes: episodes.filter(Boolean)
  };
}

function getToolCatalog(ctx: ModuleContext): ToolCatalogEntry[] {
  const metadata = ctx.profile.metadata;
  const catalog =
    metadata && typeof metadata === "object" && Array.isArray(metadata.tool_catalog)
      ? metadata.tool_catalog
      : null;

  if (!catalog) {
    return ctx.profile.tool_refs.map((name) => ({ name }));
  }

  return catalog.map((entry) =>
    entry && typeof entry === "object"
      ? {
          name: "name" in entry ? String(entry.name) : undefined,
          description: "description" in entry && typeof entry.description === "string"
            ? entry.description
            : undefined,
          sideEffectLevel:
            "sideEffectLevel" in entry &&
            (entry.sideEffectLevel === "none" ||
              entry.sideEffectLevel === "low" ||
              entry.sideEffectLevel === "medium" ||
              entry.sideEffectLevel === "high")
              ? entry.sideEffectLevel
              : undefined,
          inputSchema:
            "inputSchema" in entry && entry.inputSchema && typeof entry.inputSchema === "object"
              ? (entry.inputSchema as Record<string, unknown>)
              : undefined,
          outputSchema:
            "outputSchema" in entry && entry.outputSchema && typeof entry.outputSchema === "object"
              ? (entry.outputSchema as Record<string, unknown>)
              : undefined
        }
      : {}
  );
}

function resolveToolSideEffectLevel(
  action: ActionJson,
  toolCatalog: ToolCatalogEntry[]
): CandidateAction["side_effect_level"] | undefined {
  if (action.action_type !== "call_tool" || !action.tool_name) {
    return undefined;
  }

  const matched = toolCatalog.find((tool) => tool.name === action.tool_name);
  return matched?.sideEffectLevel;
}

function buildFallbackAskUserAction(error: unknown): Omit<CandidateAction, "action_id"> {
  if (isRetriableJsonParseError(error)) {
    return {
      action_type: "ask_user",
      title: "Retry the request",
      description:
        "The model returned incomplete structured output before a valid action could be selected. Retry the request or narrow the task if it keeps happening.",
      expected_outcome: "Collect a request that can be executed safely.",
      side_effect_level: "none"
    };
  }

  if (isProviderQuotaError(error)) {
    return {
      action_type: "ask_user",
      title: "Retry later",
      description:
        "The model provider rejected the request before a valid action could be selected because the current quota or rate limit was exceeded. Retry later or narrow the task.",
      expected_outcome: "Collect a request that can be retried after the provider recovers.",
      side_effect_level: "none"
    };
  }

  return {
    action_type: "ask_user",
    title: "Retry the request",
    description:
      "The model request failed before a valid action could be selected. Retry the request or narrow the task if it keeps happening.",
    expected_outcome: "Collect a request that can be executed safely.",
    side_effect_level: "none"
  };
}

function isProviderQuotaError(error: unknown): boolean {
  if (!(error instanceof Error)) {
    return false;
  }

  const message = error.message.toLowerCase();
  return (
    message.includes("429") ||
    message.includes("quota") ||
    message.includes("throttl") ||
    message.includes("限流") ||
    message.includes("配额")
  );
}
