import type {
  CandidateAction,
  Goal,
  ModuleContext,
  Proposal,
  Reasoner,
  SideEffectLevel
} from "@neurocore/protocol";
import type { OpenAICompatibleConfig } from "../config/openai-compatible-config.js";
import { debugLog } from "../debug.js";

interface ChatCompletionResponse {
  choices?: Array<{
    message?: {
      content?: string | Array<{ type?: string; text?: string }>;
    };
  }>;
}

interface ProposalJson {
  proposal_type?: Proposal["proposal_type"];
  salience_score?: number;
  confidence?: number;
  risk?: number;
  explanation?: string;
  payload?: Record<string, unknown>;
}

interface ActionJson {
  action_type?: CandidateAction["action_type"];
  title?: string;
  description?: string;
  tool_name?: string;
  tool_args?: Record<string, unknown>;
  expected_outcome?: string;
  preconditions?: string[];
  side_effect_level?: CandidateAction["side_effect_level"];
}

interface PlanResultJson {
  proposals?: ProposalJson[];
}

interface RespondResultJson {
  actions?: ActionJson[];
}

interface ToolCatalogEntry {
  name?: string;
  description?: string;
  sideEffectLevel?: SideEffectLevel;
  inputSchema?: Record<string, unknown>;
  outputSchema?: Record<string, unknown>;
}

interface NormalizedActionJson extends ActionJson {
  action_type: CandidateAction["action_type"];
}

export class OpenAICompatibleReasoner implements Reasoner {
  public readonly name = "openai-compatible-reasoner";

  public constructor(private readonly config: OpenAICompatibleConfig) {}

  public async plan(ctx: ModuleContext): Promise<Proposal[]> {
    const cycleId = ctx.session.current_cycle_id ?? ctx.services.generateId("cyc");
    debugLog("reasoner", "Starting planning request", {
      sessionId: ctx.session.session_id,
      cycleId,
      model: this.config.model,
      goalCount: ctx.goals.length,
      toolCount: ctx.profile.tool_refs.length
    });

    try {
      const json = await this.completeJson<PlanResultJson>(
        buildPlanSystemPrompt(),
        buildPlanUserPrompt(ctx)
      );
      const proposals = (json.proposals ?? [])
        .slice(0, 3)
        .map((proposal) => ({
          proposal_id: ctx.services.generateId("prp"),
          schema_version: ctx.profile.schema_version,
          session_id: ctx.session.session_id,
          cycle_id: cycleId,
          module_name: this.name,
          proposal_type: proposal.proposal_type ?? "plan",
          salience_score: clampScore(proposal.salience_score, 0.6),
          confidence: clampScore(proposal.confidence, 0.6),
          risk: clampScore(proposal.risk, 0.1),
          payload: proposal.payload ?? {
            summary: "Model returned no plan payload."
          },
          explanation: proposal.explanation ?? "Generated by the model-backed planning path."
        }));

      if (proposals.length > 0) {
        debugLog("reasoner", "Planning request completed", {
          sessionId: ctx.session.session_id,
          cycleId,
          proposalCount: proposals.length
        });
        return proposals;
      }
    } catch (error) {
      debugLog("reasoner", "Planning request failed, falling back to local plan", {
        sessionId: ctx.session.session_id,
        cycleId,
        errorMessage: error instanceof Error ? error.message : String(error)
      });
    }

    const fallbackProposal = buildFallbackPlanProposal(ctx, cycleId);
    debugLog("reasoner", "Using fallback local plan proposal", {
      sessionId: ctx.session.session_id,
      cycleId
    });
    return [fallbackProposal];
  }

  public async respond(ctx: ModuleContext): Promise<CandidateAction[]> {
    const currentInputContent =
      typeof ctx.runtime_state.current_input_content === "string"
        ? ctx.runtime_state.current_input_content
        : "";
    const toolCatalog = getToolCatalog(ctx);
    const knownTools = new Set(ctx.profile.tool_refs);

    debugLog("reasoner", "Starting action selection request", {
      sessionId: ctx.session.session_id,
      cycleId: ctx.session.current_cycle_id ?? "pending",
      model: this.config.model,
      toolCount: ctx.profile.tool_refs.length,
      goalCount: ctx.goals.length,
      contextChars: currentInputContent.length
    });

    let json: RespondResultJson;
    try {
      json = await this.completeJson<RespondResultJson>(
        buildRespondSystemPrompt(),
        buildRespondUserPrompt(ctx)
      );
    } catch (error) {
      debugLog("reasoner", "Action selection request failed, using fallback ask_user action", {
        sessionId: ctx.session.session_id,
        cycleId: ctx.session.current_cycle_id ?? "pending",
        errorMessage: error instanceof Error ? error.message : String(error)
      });
      return [
        {
          action_id: ctx.services.generateId("act"),
          action_type: "ask_user",
          title: "Clarify the request",
          description:
            "The model response could not be parsed into a valid action. Ask the user to restate or narrow the request.",
          expected_outcome: "Collect a request that can be executed safely.",
          side_effect_level: "none"
        }
      ];
    }

    const actions = json.actions ?? [];
    if (actions.length === 0) {
      debugLog("reasoner", "Model returned no actions, using fallback ask_user action", {
        sessionId: ctx.session.session_id
      });
      return [
        {
          action_id: ctx.services.generateId("act"),
          action_type: "ask_user",
          title: "Clarify the request",
          description: "Model returned no structured actions, ask the user for clarification.",
          expected_outcome: "Collect missing information before continuing.",
          side_effect_level: "none"
        }
      ];
    }

    const mapped = actions
      .map((action) => normalizeAction(action, knownTools))
      .filter((action): action is NormalizedActionJson => action !== null)
      .map((action) => ({
        action_id: ctx.services.generateId("act"),
        action_type: action.action_type,
        title: action.title ?? "Untitled action",
        description: action.description,
        tool_name: action.tool_name,
        tool_args: action.tool_args,
        expected_outcome: action.expected_outcome,
        preconditions: action.preconditions,
        side_effect_level:
          action.side_effect_level ?? resolveToolSideEffectLevel(action, toolCatalog) ?? inferSideEffectLevel(action)
      }));

    if (mapped.length === 0) {
      debugLog("reasoner", "Model actions were invalid for the available tool catalog", {
        sessionId: ctx.session.session_id,
        cycleId: ctx.session.current_cycle_id ?? "pending"
      });
      return [
        {
          action_id: ctx.services.generateId("act"),
          action_type: "ask_user",
          title: "Clarify the request",
          description: "Model proposed unsupported tool actions, ask the user for clarification.",
          expected_outcome: "Collect a request that matches the available toolset.",
          side_effect_level: "none"
        }
      ];
    }

    debugLog("reasoner", "Action selection completed", {
      sessionId: ctx.session.session_id,
      actionCount: mapped.length,
      actionTypes: mapped.map((action) => action.action_type),
      toolNames: mapped.map((action) => action.tool_name).filter(Boolean)
    });

    return mapped;
  }

  private async completeJson<T>(systemPrompt: string, userPrompt: string): Promise<T> {
    const controller = new AbortController();
    const timeoutMs = this.config.timeoutMs ?? 60_000;
    const timeout = setTimeout(() => controller.abort(), timeoutMs);
    const url = resolveChatCompletionsUrl(this.config.apiUrl);
    const startedAt = Date.now();

    try {
      debugLog("reasoner", "Sending model request", {
        model: this.config.model,
        url,
        timeoutMs,
        systemPromptChars: systemPrompt.length,
        userPromptChars: userPrompt.length
      });

      const response = await fetch(url, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: `Bearer ${this.config.bearerToken}`,
          ...this.config.headers
        },
        body: JSON.stringify({
          model: this.config.model,
          temperature: 0.2,
          max_tokens: 1024*100,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt }
          ]
        }),
        signal: controller.signal
      });

      const latencyMs = Date.now() - startedAt;
      debugLog("reasoner", "Received model response headers", {
        model: this.config.model,
        url,
        status: response.status,
        ok: response.ok,
        latencyMs
      });

      if (!response.ok) {
        const body = await response.text();
        debugLog("reasoner", "Model request failed", {
          model: this.config.model,
          status: response.status,
          latencyMs,
          errorPreview: body.slice(0, 300)
        });
        throw new Error(
          `Model request failed with ${response.status} ${response.statusText}: ${body}`
        );
      }

      const data = (await response.json()) as ChatCompletionResponse;
      const content = extractContent(data);
      debugLog("reasoner", "Parsed model response content", {
        model: this.config.model,
        latencyMs,
        contentChars: content.length,
        contentPreview: content
      });
      return parseJsonResponse<T>(content);
    } catch (error) {
      const latencyMs = Date.now() - startedAt;
      debugLog("reasoner", "Model request threw", {
        model: this.config.model,
        url,
        latencyMs,
        errorName: error instanceof Error ? error.name : "UnknownError",
        errorMessage: error instanceof Error ? error.message : String(error)
      });
      throw error;
    } finally {
      clearTimeout(timeout);
    }
  }
}

function resolveChatCompletionsUrl(apiUrl: string): string {
  const normalized = apiUrl.replace(/\/+$/, "");
  if (normalized.endsWith("/chat/completions")) {
    return normalized;
  }
  return `${normalized}/chat/completions`;
}

function extractContent(response: ChatCompletionResponse): string {
  const content = response.choices?.[0]?.message?.content;
  if (typeof content === "string") {
    return stripMarkdownCodeFence(content);
  }
  if (Array.isArray(content)) {
    const joined = content.map((part) => part.text ?? "").join("");
    return stripMarkdownCodeFence(joined);
  }
  throw new Error("Model response did not include message content.");
}

function stripMarkdownCodeFence(value: string): string {
  return value.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim();
}

function parseJsonResponse<T>(content: string): T {
  try {
    return JSON.parse(content) as T;
  } catch {
    const extracted = extractFirstJsonObject(content);
    return JSON.parse(extracted) as T;
  }
}

function extractFirstJsonObject(content: string): string {
  const start = content.search(/[\[{]/);
  if (start < 0) {
    throw new Error("Model response did not contain JSON.");
  }

  const stack: string[] = [];
  let inString = false;
  let escaped = false;

  for (let index = start; index < content.length; index += 1) {
    const char = content[index];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
      continue;
    }

    if (char === "{" || char === "[") {
      stack.push(char);
      continue;
    }

    if (char === "}" || char === "]") {
      const expected = char === "}" ? "{" : "[";
      if (stack.at(-1) === expected) {
        stack.pop();
      }
      if (stack.length === 0) {
        return content.slice(start, index + 1);
      }
    }
  }

  if (!inString && stack.length > 0) {
    const suffix = stack
      .slice()
      .reverse()
      .map((char) => (char === "{" ? "}" : "]"))
      .join("");
    return `${content.slice(start)}${suffix}`;
  }

  throw new Error("Model response contained incomplete JSON.");
}

function clampScore(value: number | undefined, fallback: number): number {
  if (typeof value !== "number" || Number.isNaN(value)) {
    return fallback;
  }
  return Math.max(0, Math.min(1, value));
}

function inferSideEffectLevel(action: ActionJson): CandidateAction["side_effect_level"] {
  return action.action_type === "call_tool" ? "medium" : "none";
}

function isValidActionType(value: unknown): value is CandidateAction["action_type"] {
  return (
    value === "respond" ||
    value === "ask_user" ||
    value === "call_tool" ||
    value === "update_goal" ||
    value === "write_memory" ||
    value === "delegate" ||
    value === "wait" ||
    value === "complete" ||
    value === "abort"
  );
}

function normalizeAction(
  action: ActionJson,
  knownTools: Set<string>
): NormalizedActionJson | null {
  let actionType = isValidActionType(action.action_type) ? action.action_type : undefined;
  let toolName = action.tool_name;

  if (!actionType && typeof action.action_type === "string" && knownTools.has(action.action_type)) {
    actionType = "call_tool";
    toolName ??= action.action_type;
  }

  if (!actionType && typeof toolName === "string" && knownTools.has(toolName)) {
    actionType = "call_tool";
  }

  if (!actionType) {
    actionType = "respond";
  }

  if (actionType === "call_tool") {
    if (typeof toolName !== "string" || !knownTools.has(toolName)) {
      return null;
    }
  } else {
    toolName = undefined;
  }

  return {
    ...action,
    action_type: actionType,
    tool_name: toolName
  };
}

function buildPlanSystemPrompt(): string {
  return [
    "You are the planning module of a structured agent runtime.",
    "Return JSON only.",
    'Output shape: {"proposals":[{"proposal_type":"plan","salience_score":0.0,"confidence":0.0,"risk":0.0,"explanation":"...","payload":{"summary":"..."}}]}',
    "Use scores in the range [0,1].",
    "Ground the plan in the current goals, available tools, recalled memory, and current context.",
    "Do not include markdown or commentary outside JSON."
  ].join("\n");
}

function buildRespondSystemPrompt(): string {
  return [
    "Structured agent runtime action selector.",
    "Return JSON only.",
    'Shape: {"actions":[{"action_type":"ask_user|respond|call_tool|complete|abort","title":"...","description":"...","tool_name":"...","tool_args":{},"expected_outcome":"...","preconditions":["..."],"side_effect_level":"none|low|medium|high"}]}',
    "Use at most 2 actions.",
    "Only use tool names provided in the tool catalog.",
    "Use recalled memory and previous tool observations to decide the next step.",
    "If prior evidence is insufficient, call the next necessary tool. If evidence is sufficient, respond or complete.",
    "For destructive or production-impacting tools, preserve a high side_effect_level and include preconditions.",
    "For respond or complete actions, put the exact user-facing answer in description. Do not write meta-instructions like 'provide diagnosis' or 'summarize result'.",
    "Prefer concise outputs."
  ].join("\n");
}

function buildPlanUserPrompt(ctx: ModuleContext): string {
  const memoryRecall = Array.isArray(ctx.runtime_state.memory_recall_proposals)
    ? ctx.runtime_state.memory_recall_proposals.map(summarizeMemoryProposal)
    : [];

  return JSON.stringify(
    {
      role: ctx.profile.role,
      domain: ctx.profile.domain,
      activeGoals: ctx.goals.map(summarizeGoal),
      availableTools: getToolCatalog(ctx),
      memoryRecall,
      workspace: ctx.workspace
        ? {
            contextSummary: ctx.workspace.context_summary,
            candidateActions: ctx.workspace.candidate_actions,
            memoryDigest: ctx.workspace.memory_digest
          }
        : null
    },
    null,
    2
  );
}

function buildRespondUserPrompt(ctx: ModuleContext): string {
  const memoryRecall = Array.isArray(ctx.runtime_state.memory_recall_proposals)
    ? ctx.runtime_state.memory_recall_proposals.map(summarizeMemoryProposal)
    : [];

  return JSON.stringify(
    {
      role: ctx.profile.role,
      goals: ctx.goals.map(summarizeGoal),
      tools: getToolCatalog(ctx),
      memoryRecall,
      context: typeof ctx.runtime_state.current_input_content === "string"
        ? ctx.runtime_state.current_input_content
        : ctx.workspace?.context_summary ?? null,
      inputMetadata: ctx.runtime_state.current_input_metadata ?? null,
      workspace: ctx.workspace
        ? {
            memoryDigest: ctx.workspace.memory_digest,
            candidateActions: ctx.workspace.candidate_actions
          }
        : null
    },
    null,
    2
  );
}

function buildFallbackPlanProposal(
  ctx: ModuleContext,
  cycleId: string
): Proposal {
  const goalTitles = ctx.goals.map((goal) => goal.title).filter(Boolean);
  const summary =
    goalTitles.length > 0
      ? `Pursue active goals: ${goalTitles.join("; ")}`
      : `Act according to role: ${ctx.profile.role}`;

  return {
    proposal_id: ctx.services.generateId("prp"),
    schema_version: ctx.profile.schema_version,
    session_id: ctx.session.session_id,
    cycle_id: cycleId,
    module_name: "openai-compatible-reasoner",
    proposal_type: "plan",
    salience_score: 0.6,
    confidence: 0.6,
    risk: 0.1,
    payload: {
      summary,
      toolRefs: ctx.profile.tool_refs
    },
    explanation: "Fallback local plan after model planning failed."
  };
}

function summarizeGoal(goal: Goal) {
  return {
    goalId: goal.goal_id,
    title: goal.title,
    description: goal.description,
    status: goal.status,
    priority: goal.priority
  };
}

function summarizeMemoryProposal(proposal: unknown) {
  if (!proposal || typeof proposal !== "object") {
    return null;
  }

  const payload =
    "payload" in proposal && proposal.payload && typeof proposal.payload === "object"
      ? proposal.payload
      : null;
  const entries =
    payload && "entries" in payload && Array.isArray(payload.entries)
      ? payload.entries.map((entry) =>
          typeof entry === "object" && entry !== null ? (entry as { summary?: string }).summary : null
        )
      : [];
  const episodes =
    payload && "episodes" in payload && Array.isArray(payload.episodes)
      ? payload.episodes.map((episode) => {
          if (!episode || typeof episode !== "object") {
            return null;
          }
          const metadata =
            "metadata" in episode && episode.metadata && typeof episode.metadata === "object"
              ? episode.metadata
              : null;
          return {
            selectedStrategy:
              "selected_strategy" in episode ? episode.selected_strategy : undefined,
            outcome: "outcome" in episode ? episode.outcome : undefined,
            outcomeSummary:
              "outcome_summary" in episode ? episode.outcome_summary : undefined,
            toolName:
              metadata && "tool_name" in metadata ? metadata.tool_name : undefined
          };
        })
      : [];

  return {
    module: "module_name" in proposal ? proposal.module_name : undefined,
    explanation: "explanation" in proposal ? proposal.explanation : undefined,
    entries: entries.filter(Boolean),
    episodes: episodes.filter(Boolean)
  };
}

function getToolCatalog(ctx: ModuleContext): ToolCatalogEntry[] {
  const metadata = ctx.profile.metadata;
  const catalog =
    metadata && typeof metadata === "object" && Array.isArray(metadata.tool_catalog)
      ? metadata.tool_catalog
      : null;

  if (!catalog) {
    return ctx.profile.tool_refs.map((name) => ({ name }));
  }

  return catalog.map((entry) =>
    entry && typeof entry === "object"
      ? {
          name: "name" in entry ? String(entry.name) : undefined,
          description: "description" in entry && typeof entry.description === "string"
            ? entry.description
            : undefined,
          sideEffectLevel:
            "sideEffectLevel" in entry &&
            (entry.sideEffectLevel === "none" ||
              entry.sideEffectLevel === "low" ||
              entry.sideEffectLevel === "medium" ||
              entry.sideEffectLevel === "high")
              ? entry.sideEffectLevel
              : undefined,
          inputSchema:
            "inputSchema" in entry && entry.inputSchema && typeof entry.inputSchema === "object"
              ? (entry.inputSchema as Record<string, unknown>)
              : undefined,
          outputSchema:
            "outputSchema" in entry && entry.outputSchema && typeof entry.outputSchema === "object"
              ? (entry.outputSchema as Record<string, unknown>)
              : undefined
        }
      : {}
  );
}

function resolveToolSideEffectLevel(
  action: ActionJson,
  toolCatalog: ToolCatalogEntry[]
): CandidateAction["side_effect_level"] | undefined {
  if (action.action_type !== "call_tool" || !action.tool_name) {
    return undefined;
  }

  const matched = toolCatalog.find((tool) => tool.name === action.tool_name);
  return matched?.sideEffectLevel;
}
